### ISSUE TITLE
Infinite Loop with Webhook

### ISSUE THREAD

**Issue by om3g4** [digital2k/PHP-TelegramLibrary#1]
Hey!

Thanks for the library.
When i try to run your sample code and add my URL to Telegram via Webhook the Bot never stops sending messages to the account.

Am I missing something here?

**Comment by tekook** [comment]
The code sample is desinged to be a demonstration. The bot will always respond to a text message with the given ReplyMarkup.

Only if you answer with "A" it will say ok and don't send anything more.

Can you provide me with more information?

**Comment by tekook** [comment]
Does it send the same message over and over again like always "hello ..."?

If yes, your webserver might not be responding with 200 - OK so the telegram servers will push the update again and again

**Comment by om3g4** [comment]
Yeah, you were absolutely right. Webserver did not respond 200. It is fixed now and I feel like an idiot.

Thank you so much and have a great day!

**Comment by tekook** [comment]
No problem mate! :)
