### ISSUE TITLE
fatal error using WAMP

### ISSUE THREAD

**Issue by ameer** [digital2k/PHP-TelegramLibrary#3]
Hi, I tested the project on wamp but got this error
![image](https://cloud.githubusercontent.com/assets/7665183/8892854/a46f0162-3387-11e5-81f0-be2e1ae915eb.png)

I'm using the below example in my index.php file:

```
<?php
function __autoload($class_name) {
    include $class_name . '.php';
}

use Tekook\TelegramLibrary;

$telegram = new TelegramLibrary\TelegramBotApi("119258014:AAFP2QbPBazeulQrRvxLJyVd-jHLrRElByw");


$eventHandler = $telegram->getEventHandler();
$eventHandler->addHook(TelegramLibrary\Events::TEXT,
        function(\Tekook\TelegramLibrary\Types\Message $message) {
    if ($message->getText() == "A") {
        $message->reply("OK", ["reply_markup" => new TelegramLibrary\Markups\ReplyKeyboardHide()]);
    } else {
        $message->reply("Hello, " . $message->getFrom()->getFirstName() . " please answer A!",
                [
            "reply_markup" => new TelegramLibrary\Markups\ReplyKeyboardMarkup([
                ["A", "B"],
                ["C", "D"],
                ["E", "F"],
                    ])
        ]);
    }
});

$telegram->pushUpdate();
```

**Comment by tekook** [comment]
I'll have a look later, I'm currently on the go...

My first guess would be that you are not using the webhook provided by telegram. If the api is not called by telegram servers you need to use the receive updates method! I'll be back this evening and explain s but better

**Comment by tekook** [comment]
Hello amir,

Sport for replying so late. I checked and my guess was right. You are not using the webhook method and thus cannot use pushUpdate() as it expects the get a json request by the telegram servers. 

If you don't want to use the webhook, you can use the getUpdates () method and pass them on the the eventHandler (using the getEventHandler()  method and then the handle() method of the  event handler )

For more information how the update calling work please read the official documentation of the telegrambotapi (link in readme.MD)

Hope I could help!
